# Generated by Django 3.0.5 on 2020-08-11 23:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expediente', '0001_initial'),
        ('utilidades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='direcciones',
            name='no_radicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expediente.Expediente'),
        ),
        migrations.AddField(
            model_name='direcciones',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='actuacionposterior',
            name='cod_tipo_acto_administrativo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilidades.TipoActoAdministrativo'),
        ),
        migrations.AddField(
            model_name='actuacionposterior',
            name='no_radicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expediente.Expediente'),
        ),
        migrations.AddField(
            model_name='actuacionposterior',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='informaciongeneral',
            name='alcaldia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utilidades.Alcaldia'),
        ),
        migrations.AddField(
            model_name='informaciongeneral',
            name='modalidades',
            field=models.ManyToManyField(blank=True, to='utilidades.Modalidades'),
        ),
        migrations.AddField(
            model_name='informaciongeneral',
            name='tramite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilidades.Tramite'),
        ),
        migrations.AddField(
            model_name='informaciongeneral',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='actuacionposterior',
            constraint=models.UniqueConstraint(fields=('no_radicacion', 'acto_administrativo'), name='unica_actuacion'),
        ),
    ]
