# Generated by Django 3.0.5 on 2020-08-14 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0002_auto_20200813_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informaciongeneral',
            name='no_radicacion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='expediente_informacion', serialize=False, to='expediente.Expediente'),
        ),
    ]
