# Generated by Django 3.0.5 on 2020-08-13 16:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utilidades', '0001_initial'),
        ('expediente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('numero_caja', models.PositiveIntegerField()),
                ('año', models.PositiveIntegerField(choices=[(2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020)], default=2020, verbose_name='Año')),
            ],
            options={
                'verbose_name': 'Caja',
                'verbose_name_plural': 'Cajas',
                'ordering': ['-año'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('tipo_documento', models.PositiveIntegerField(choices=[(1, 'Folios'), (2, 'Arquitectura'), (3, 'Estructural')], verbose_name='Tipo de documento')),
                ('cantidad', models.PositiveIntegerField(default=0, verbose_name='Cantidad')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilidades.Documento')),
                ('no_radicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expediente.Expediente')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-document'],
            },
        ),
        migrations.CreateModel(
            name='Carpeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_carpeta', models.PositiveIntegerField(choices=[(1, 'Folios'), (2, 'Arquitectura'), (3, 'Anexos')], verbose_name='Tipo de carpeta')),
                ('cantidad_ini', models.PositiveIntegerField(default=0, verbose_name='Cantidad inicial')),
                ('cantidad_final', models.PositiveIntegerField(default=0, verbose_name='Cantidad final')),
                ('carpeta_inicial', models.PositiveIntegerField(verbose_name='Carpeta inicial')),
                ('carpeta_final', models.PositiveIntegerField(verbose_name='Carpeta final')),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transferir.Caja')),
                ('no_radicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expediente.Expediente')),
            ],
            options={
                'verbose_name': 'Carpeta',
                'verbose_name_plural': 'Carpetas',
                'ordering': ['-no_radicacion'],
            },
        ),
    ]
