# Generated by Django 3.0.5 on 2020-08-12 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilidades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modalidades',
            name='modalidad',
            field=models.CharField(max_length=30, verbose_name='Código de modalidad'),
        ),
    ]
