# Generated by Django 3.0.5 on 2020-08-12 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilidades', '0002_auto_20200811_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoactoadministrativo',
            name='tipo_acto_administrativo',
            field=models.CharField(max_length=50, unique=True, verbose_name='Tipo de acto administrativo'),
        ),
    ]
